// Client/constants/Texts.js
export const Texts = {
  en: {
    descriptionOne: `Hi I'm Geyson and im passionate about technology and `,
    descriptionTwo: ', and I am always looking to learn new things.',
    portfolio: 'Portfolio',
    about: 'About',
    projects: 'Projects',
    contact: 'Contact',
    webdeveloper: 'Web Developer',
    programming: 'Programming',
    frontDev: 'Front-End Developer',
    backDev: 'Back-End Developer',
    frontText: "I love bringing my ideas to life; I truly enjoy the process.",
    backText: "If you can imagine it, I can program it.",
    languageiuse: "Languages I use ",
    devtools: "Dev Tools",
    blackjackdescription: "A simple BlackJack game built using ReactJS with betting functionality.",
    controlzdescription: "ControlZ is a fitness application designed to help you achieve your health goals",
  },
  es: {
    descriptionOne: `Hola soy Geyson y me apasiona la tecnología y `,
    descriptionTwo: ', y siempre estoy buscando aprender cosas nuevas.',
    portfolio: 'Portafolio',
    about: 'Sobre mi',
    projects: 'Proyectos',
    contact: 'Contacto',
    webdeveloper: 'Desarrollador Web',
    programming: 'Programación',
    frontDev: 'Desarrollador Front-End',
    backDev: 'Desarrollador Back-End',
    frontText: "Me encanta llevar mis ideas a la vida; realmente disfruto el proceso.",
    backText: "Si puedes imaginarlo, puedo programarlo.",
    languageiuse: "Lenguajes que uso :",
    devtools: "Herramientas de Desarrollo"
  },
};
